name: flappy_translator
description: A Flutter internationalized strings generator. It enables you to writte all your i18n strings in a CSV and automatically generate Strings in your app.
version: 1.2.2
homepage: https://github.com/smartnsoft/FlappyTranslator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.0
  yaml: ^3.1.0
  dart_style: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
